version: '3'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - SECRET_KEY=your_secret_key
      - DEBUG=False
    depends_on:
      - db
    restart: unless-stopped

  db:
    image: postgres:12
    environment:
      - POSTGRES_USER=your_postgres_user
      - POSTGRES_PASSWORD=your_postgres_password
      - POSTGRES_DB=your_postgres_db
    restart: unless-stopped